### ISSUE TITLE
issue with kotti -> bellevue

### ISSUE THREAD

**Issue by derhuerst** [derhuerst/vbb-telegram#3]
```
53306530 '8/10/2016' '3:15 PM' '/r⁣ Get routes from A to B.'
53306530 '8/10/2016' '3:15 PM' 'kotti'
53306530 '8/10/2016' '3:15 PM' 'bellevue'
53306530 '8/10/2016' '3:15 PM' 'now'
TypeError: r.map is not a function
    at Object.routes (/root/vbb-telegram/lib/render.js:72:3)
    at /root/vbb-telegram/commands/routes.js:44:28
    at next (native)
    at resolved (/root/vbb-telegram/node_modules/so/lib/so.js:30:46)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by derhuerst** [comment]
Seems to be fixed as of [derhuerst/vbb-rest#43b25e5](https://github.com/derhuerst/vbb-rest/commit/43b25e5de957d7bf37e22e64817af81eb41ce983).
